name: SSE CI/CD
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install clang-format"
        run: sudo apt-get install -y clang-format
      - name: "Clang check src"
        run: clang-format --dry-run --Werror src/*
      - name: "Clang check tests"
        run: clang-format --dry-run --Werror tests/*cpp
